source 'https://rubygems.org'

gem 'allure-cucumber'
gem 'capybara'
gem 'cucumber'
gem 'ffi'
gem 'httparty'
gem 'json'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'site_prism'